---
:server: irc.freenode.net

:abiquo:
  :host: mothership
  :user: admin
  :password: xabiquo

:gitdude:
  :repos:
    - :name: Abiquo
      :path: '~/repos/platform'
        
:nick: elfari
:channels:
  - "#foobarslkj chan-key"
:timeout: 10000

:elfari:
  :url: 'localhost'
  :port: 4567


:mplayer: '/opt/local/bin/mplayer' 


:database: 'config/db/database'

:melee:
  :channel: "#foobarslkj chan-key"

:vlc:
  :bin: '/Applications/VLC.app/Contents/MacOS/VLC'
  :host: 'localhost'
  :port: 4000
  :args: '--ignore-config -I lua --lua-intf cli --no-video' 
