---
:server: irc.freenode.net

:abiquo:
  :host: mothership
  :user: admin
  :password: xabiquo

:gitdude:
  :repos:
    - :name: Abiquo
      :path: '/Users/rubiojr/git/abiquo'
    - :name: Abiquo Enterprise
      :path: '/Users/rubiojr/git/abiquo-enterprise'
        
:nick: elfari2
:channels:
  - "#foobarslkj chan-key"
:timeout: 10000

:elfari:
  :url: 'localhost'
  :port: 4567
:mplayer: '/usr/bin/mplayer' 


:database: 'config/db/database'

:melee:
  :channel: "#foobarslkj chan-key"
